### ISSUE TITLE
Paper

### ISSUE THREAD

**Issue by Golriz-code** [ark1234/NeurIPS2023-InfoCD#1]
Hello,
Where can I find the link for the paper, InfoCD?
Thanks

**Comment by ark1234** [comment]
Thank you so much for being interested in our work, we have been busy working on other work recently, we will put it into Arxiv soon, and the paper will be found in Openreview soon too.

Again, thank you very much for being interested in our work!

**Comment by ark1234** [comment]
You can leave your email for me, I can send you the paper first!

**Comment by Golriz-code** [comment]
> You can leave your email for me, I can send you the paper first!

Thanks!
golriz.hosseinimanesh@polymtl.ca
